FROM ruby:3.2.2-alpine3.18

RUN apk --no-cache add \
    build-base \
    vips-dev \
    bash \
    libffi-dev \
    tzdata \
    postgresql \
    nodejs \
    npm \
    git \ 
    libpq-dev \
  && gem install bundler:2.4.13 \
  && gem install mailcatcher

WORKDIR /app

COPY docker/entrypoint.sh /app/docker/entrypoint.sh

ENV RAILS_LOG_TO_STDOUT="1" \
    RAILS_SERVE_STATIC_FILES="true" 

COPY Gemfile* ./

RUN bundle install

COPY . /app/

RUN bundle exec rails assets:precompile

ENTRYPOINT ["/app/bin/docker-entrypoint.sh"]

